-- Seed: categorias, exercicios e a ligação entre eles
-- Gerado a partir do catálogo do protótipo original.

do $$
declare
  cat_id uuid;
  ex_id uuid;
begin
  insert into categorias (parte, nome, nota, ordem) values ('A', 'Membros Inferiores (Geral)', 'Cadeia inferior, bilateral ou unilateral', 1) returning id into cat_id;
  insert into exercicios (nome) select 'Agachamento Back / Front Squat (Barra / Smith)' where not exists (select 1 from exercicios where nome = 'Agachamento Back / Front Squat (Barra / Smith)');
  select id into ex_id from exercicios where nome = 'Agachamento Back / Front Squat (Barra / Smith)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Leg Press 45º / Horizontal' where not exists (select 1 from exercicios where nome = 'Leg Press 45º / Horizontal');
  select id into ex_id from exercicios where nome = 'Leg Press 45º / Horizontal';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Goblet Squat (Halter / Kettlebell)' where not exists (select 1 from exercicios where nome = 'Goblet Squat (Halter / Kettlebell)');
  select id into ex_id from exercicios where nome = 'Goblet Squat (Halter / Kettlebell)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Passadas / Walk Lunges' where not exists (select 1 from exercicios where nome = 'Passadas / Walk Lunges');
  select id into ex_id from exercicios where nome = 'Passadas / Walk Lunges';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Step-Up na Box / Banco' where not exists (select 1 from exercicios where nome = 'Step-Up na Box / Banco');
  select id into ex_id from exercicios where nome = 'Step-Up na Box / Banco';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Peso Morto / Deadlift Convencional' where not exists (select 1 from exercicios where nome = 'Peso Morto / Deadlift Convencional');
  select id into ex_id from exercicios where nome = 'Peso Morto / Deadlift Convencional';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Cadeira Extensora' where not exists (select 1 from exercicios where nome = 'Cadeira Extensora');
  select id into ex_id from exercicios where nome = 'Cadeira Extensora';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento Búlgaro' where not exists (select 1 from exercicios where nome = 'Agachamento Búlgaro');
  select id into ex_id from exercicios where nome = 'Agachamento Búlgaro';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Cossack Squat' where not exists (select 1 from exercicios where nome = 'Cossack Squat');
  select id into ex_id from exercicios where nome = 'Cossack Squat';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento Sissi' where not exists (select 1 from exercicios where nome = 'Agachamento Sissi');
  select id into ex_id from exercicios where nome = 'Agachamento Sissi';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Parte Anterior das Pernas (Quadríceps)', 'Extensão de joelho, vetor vertical', 2) returning id into cat_id;
  insert into exercicios (nome) select 'Cadeira Extensora (Bilateral / Unilateral)' where not exists (select 1 from exercicios where nome = 'Cadeira Extensora (Bilateral / Unilateral)');
  select id into ex_id from exercicios where nome = 'Cadeira Extensora (Bilateral / Unilateral)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento Hack na Smith Machine' where not exists (select 1 from exercicios where nome = 'Agachamento Hack na Smith Machine');
  select id into ex_id from exercicios where nome = 'Agachamento Hack na Smith Machine';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Leg Press com pés em posição baixa' where not exists (select 1 from exercicios where nome = 'Leg Press com pés em posição baixa');
  select id into ex_id from exercicios where nome = 'Leg Press com pés em posição baixa';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento Frontal (Front Squat)' where not exists (select 1 from exercicios where nome = 'Agachamento Frontal (Front Squat)');
  select id into ex_id from exercicios where nome = 'Agachamento Frontal (Front Squat)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento Sissi (Livre / Smith)' where not exists (select 1 from exercicios where nome = 'Agachamento Sissi (Livre / Smith)');
  select id into ex_id from exercicios where nome = 'Agachamento Sissi (Livre / Smith)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Step-Down Controlado na Box' where not exists (select 1 from exercicios where nome = 'Step-Down Controlado na Box');
  select id into ex_id from exercicios where nome = 'Step-Down Controlado na Box';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Extensão de Joelho com Caneleira / Elástico' where not exists (select 1 from exercicios where nome = 'Extensão de Joelho com Caneleira / Elástico');
  select id into ex_id from exercicios where nome = 'Extensão de Joelho com Caneleira / Elástico';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento com Bola Suíça na Parede' where not exists (select 1 from exercicios where nome = 'Agachamento com Bola Suíça na Parede');
  select id into ex_id from exercicios where nome = 'Agachamento com Bola Suíça na Parede';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Parte Posterior das Pernas (Isquiotibiais)', 'Flexão de joelho e hip hinge', 3) returning id into cat_id;
  insert into exercicios (nome) select 'Peso Morto Romeno (RDL com Barra / Halteres)' where not exists (select 1 from exercicios where nome = 'Peso Morto Romeno (RDL com Barra / Halteres)');
  select id into ex_id from exercicios where nome = 'Peso Morto Romeno (RDL com Barra / Halteres)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Stiff (Barra / Halteres)' where not exists (select 1 from exercicios where nome = 'Stiff (Barra / Halteres)');
  select id into ex_id from exercicios where nome = 'Stiff (Barra / Halteres)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Cadeira Flexora (Bilateral / Unilateral)' where not exists (select 1 from exercicios where nome = 'Cadeira Flexora (Bilateral / Unilateral)');
  select id into ex_id from exercicios where nome = 'Cadeira Flexora (Bilateral / Unilateral)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Flexão de Joelhos na Bola Suíça / TRX / Sliders' where not exists (select 1 from exercicios where nome = 'Flexão de Joelhos na Bola Suíça / TRX / Sliders');
  select id into ex_id from exercicios where nome = 'Flexão de Joelhos na Bola Suíça / TRX / Sliders';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Good Morning (Barra no Rack)' where not exists (select 1 from exercicios where nome = 'Good Morning (Barra no Rack)');
  select id into ex_id from exercicios where nome = 'Good Morning (Barra no Rack)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Single-Leg RDL (Halter / Kettlebell)' where not exists (select 1 from exercicios where nome = 'Single-Leg RDL (Halter / Kettlebell)');
  select id into ex_id from exercicios where nome = 'Single-Leg RDL (Halter / Kettlebell)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Kickstand RDL (B-Stance)' where not exists (select 1 from exercicios where nome = 'Kickstand RDL (B-Stance)');
  select id into ex_id from exercicios where nome = 'Kickstand RDL (B-Stance)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Glúteos (Máximo, Médio e Mínimo)', 'Extensão de anca, abdução e rotação externa', 4) returning id into cat_id;
  insert into exercicios (nome) select 'Hip Thrust (Barra / Smith / Unilateral)' where not exists (select 1 from exercicios where nome = 'Hip Thrust (Barra / Smith / Unilateral)');
  select id into ex_id from exercicios where nome = 'Hip Thrust (Barra / Smith / Unilateral)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Glute Bridge (Chão / Banco / Bola Suíça)' where not exists (select 1 from exercicios where nome = 'Glute Bridge (Chão / Banco / Bola Suíça)');
  select id into ex_id from exercicios where nome = 'Glute Bridge (Chão / Banco / Bola Suíça)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Coice de Glúteo / Glute Kickback (Polia / Caneleiras)' where not exists (select 1 from exercicios where nome = 'Coice de Glúteo / Glute Kickback (Polia / Caneleiras)');
  select id into ex_id from exercicios where nome = 'Coice de Glúteo / Glute Kickback (Polia / Caneleiras)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Máquina Abdutora Sentada' where not exists (select 1 from exercicios where nome = 'Máquina Abdutora Sentada');
  select id into ex_id from exercicios where nome = 'Máquina Abdutora Sentada';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Abdução de Anca na Polia Baixa' where not exists (select 1 from exercicios where nome = 'Abdução de Anca na Polia Baixa');
  select id into ex_id from exercicios where nome = 'Abdução de Anca na Polia Baixa';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Clamshell (Ostra) com Elástico / Miniband' where not exists (select 1 from exercicios where nome = 'Clamshell (Ostra) com Elástico / Miniband');
  select id into ex_id from exercicios where nome = 'Clamshell (Ostra) com Elástico / Miniband';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento Búlgaro (com inclinação de tronco)' where not exists (select 1 from exercicios where nome = 'Agachamento Búlgaro (com inclinação de tronco)');
  select id into ex_id from exercicios where nome = 'Agachamento Búlgaro (com inclinação de tronco)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Lunge Curvado / Curtsy Lunge' where not exists (select 1 from exercicios where nome = 'Lunge Curvado / Curtsy Lunge');
  select id into ex_id from exercicios where nome = 'Lunge Curvado / Curtsy Lunge';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Step-Up Alto na Box' where not exists (select 1 from exercicios where nome = 'Step-Up Alto na Box');
  select id into ex_id from exercicios where nome = 'Step-Up Alto na Box';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Adutores', 'Face interna da coxa e estabilização pélvica', 5) returning id into cat_id;
  insert into exercicios (nome) select 'Máquina Adutora Sentada' where not exists (select 1 from exercicios where nome = 'Máquina Adutora Sentada');
  select id into ex_id from exercicios where nome = 'Máquina Adutora Sentada';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Adutor Copenhaga no Banco (Copenhagen Plank)' where not exists (select 1 from exercicios where nome = 'Adutor Copenhaga no Banco (Copenhagen Plank)');
  select id into ex_id from exercicios where nome = 'Adutor Copenhaga no Banco (Copenhagen Plank)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Adução de Anca na Polia Baixa' where not exists (select 1 from exercicios where nome = 'Adução de Anca na Polia Baixa');
  select id into ex_id from exercicios where nome = 'Adução de Anca na Polia Baixa';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento Sumô (Barra / Smith / Kettlebell)' where not exists (select 1 from exercicios where nome = 'Agachamento Sumô (Barra / Smith / Kettlebell)');
  select id into ex_id from exercicios where nome = 'Agachamento Sumô (Barra / Smith / Kettlebell)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Leg Press com pés afastados (Sumô)' where not exists (select 1 from exercicios where nome = 'Leg Press com pés afastados (Sumô)');
  select id into ex_id from exercicios where nome = 'Leg Press com pés afastados (Sumô)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Cossack Squat' where not exists (select 1 from exercicios where nome = 'Cossack Squat');
  select id into ex_id from exercicios where nome = 'Cossack Squat';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Gémeos / Flexores do Tornozelo', 'Solear e gastrocnémio', 6) returning id into cat_id;
  insert into exercicios (nome) select 'Elevação de Calcanhares na Smith Machine (com Step)' where not exists (select 1 from exercicios where nome = 'Elevação de Calcanhares na Smith Machine (com Step)');
  select id into ex_id from exercicios where nome = 'Elevação de Calcanhares na Smith Machine (com Step)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Elevação de Calcanhares no Leg Press' where not exists (select 1 from exercicios where nome = 'Elevação de Calcanhares no Leg Press');
  select id into ex_id from exercicios where nome = 'Elevação de Calcanhares no Leg Press';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Elevação de Calcanhares Unilateral em pé com Halter' where not exists (select 1 from exercicios where nome = 'Elevação de Calcanhares Unilateral em pé com Halter');
  select id into ex_id from exercicios where nome = 'Elevação de Calcanhares Unilateral em pé com Halter';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Elevação de Calcanhares no Step com Peso Corporal' where not exists (select 1 from exercicios where nome = 'Elevação de Calcanhares no Step com Peso Corporal');
  select id into ex_id from exercicios where nome = 'Elevação de Calcanhares no Step com Peso Corporal';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Membros Superiores (Geral)', 'Cintura escapular e braços', 7) returning id into cat_id;
  insert into exercicios (nome) select 'Supino Plano / Inclinado (Barra / Halteres / Smith)' where not exists (select 1 from exercicios where nome = 'Supino Plano / Inclinado (Barra / Halteres / Smith)');
  select id into ex_id from exercicios where nome = 'Supino Plano / Inclinado (Barra / Halteres / Smith)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Press Militar / Press de Ombros' where not exists (select 1 from exercicios where nome = 'Press Militar / Press de Ombros');
  select id into ex_id from exercicios where nome = 'Press Militar / Press de Ombros';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Elevações na Barra Fixa / Puxadas' where not exists (select 1 from exercicios where nome = 'Elevações na Barra Fixa / Puxadas');
  select id into ex_id from exercicios where nome = 'Elevações na Barra Fixa / Puxadas';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada Curvada / Remada Unilateral' where not exists (select 1 from exercicios where nome = 'Remada Curvada / Remada Unilateral');
  select id into ex_id from exercicios where nome = 'Remada Curvada / Remada Unilateral';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Biceps Curl com Barra / Halteres' where not exists (select 1 from exercicios where nome = 'Biceps Curl com Barra / Halteres');
  select id into ex_id from exercicios where nome = 'Biceps Curl com Barra / Halteres';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Extensão de Tríceps na Polia / Fundos' where not exists (select 1 from exercicios where nome = 'Extensão de Tríceps na Polia / Fundos');
  select id into ex_id from exercicios where nome = 'Extensão de Tríceps na Polia / Fundos';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Parte Anterior do Tronco (Peitoral)', 'Empurrar horizontal e inclinado', 8) returning id into cat_id;
  insert into exercicios (nome) select 'Supino Plano (Barra / Halteres / Smith)' where not exists (select 1 from exercicios where nome = 'Supino Plano (Barra / Halteres / Smith)');
  select id into ex_id from exercicios where nome = 'Supino Plano (Barra / Halteres / Smith)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Supino Inclinado (Barra / Halteres / Smith)' where not exists (select 1 from exercicios where nome = 'Supino Inclinado (Barra / Halteres / Smith)');
  select id into ex_id from exercicios where nome = 'Supino Inclinado (Barra / Halteres / Smith)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Aberturas / Flyes Planos e Inclinados' where not exists (select 1 from exercicios where nome = 'Aberturas / Flyes Planos e Inclinados');
  select id into ex_id from exercicios where nome = 'Aberturas / Flyes Planos e Inclinados';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Crossover na Polia (Alta / Média / Baixa)' where not exists (select 1 from exercicios where nome = 'Crossover na Polia (Alta / Média / Baixa)');
  select id into ex_id from exercicios where nome = 'Crossover na Polia (Alta / Média / Baixa)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Flexões de Braços / Push-Ups (Chão / Banco / TRX / Bosu)' where not exists (select 1 from exercicios where nome = 'Flexões de Braços / Push-Ups (Chão / Banco / TRX / Bosu)');
  select id into ex_id from exercicios where nome = 'Flexões de Braços / Push-Ups (Chão / Banco / TRX / Bosu)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Chest Press na Polia Dupla' where not exists (select 1 from exercicios where nome = 'Chest Press na Polia Dupla');
  select id into ex_id from exercicios where nome = 'Chest Press na Polia Dupla';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Parte Posterior do Tronco (Costas)', 'Puxada vertical, horizontal e depressão escapular', 9) returning id into cat_id;
  insert into exercicios (nome) select 'Elevações na Barra Fixa (Pull-ups / Chin-ups)' where not exists (select 1 from exercicios where nome = 'Elevações na Barra Fixa (Pull-ups / Chin-ups)');
  select id into ex_id from exercicios where nome = 'Elevações na Barra Fixa (Pull-ups / Chin-ups)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Puxada Alta na Polia Dupla' where not exists (select 1 from exercicios where nome = 'Puxada Alta na Polia Dupla');
  select id into ex_id from exercicios where nome = 'Puxada Alta na Polia Dupla';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada Curvada (Barra / Halteres / Kettlebells)' where not exists (select 1 from exercicios where nome = 'Remada Curvada (Barra / Halteres / Kettlebells)');
  select id into ex_id from exercicios where nome = 'Remada Curvada (Barra / Halteres / Kettlebells)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada Unilateral ("Serrote") no Banco' where not exists (select 1 from exercicios where nome = 'Remada Unilateral ("Serrote") no Banco');
  select id into ex_id from exercicios where nome = 'Remada Unilateral ("Serrote") no Banco';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada T-Bar (Landmine)' where not exists (select 1 from exercicios where nome = 'Remada T-Bar (Landmine)');
  select id into ex_id from exercicios where nome = 'Remada T-Bar (Landmine)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada Invertida no TRX' where not exists (select 1 from exercicios where nome = 'Remada Invertida no TRX');
  select id into ex_id from exercicios where nome = 'Remada Invertida no TRX';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Lat Pullover na Polia Alta / Banco' where not exists (select 1 from exercicios where nome = 'Lat Pullover na Polia Alta / Banco');
  select id into ex_id from exercicios where nome = 'Lat Pullover na Polia Alta / Banco';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada Sentada com Cabo' where not exists (select 1 from exercicios where nome = 'Remada Sentada com Cabo');
  select id into ex_id from exercicios where nome = 'Remada Sentada com Cabo';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Ombros / Deltoides', 'Deltoide anterior, lateral e posterior', 10) returning id into cat_id;
  insert into exercicios (nome) select 'Press Militar com Barra' where not exists (select 1 from exercicios where nome = 'Press Militar com Barra');
  select id into ex_id from exercicios where nome = 'Press Militar com Barra';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Press de Ombros com Halteres / Kettlebells' where not exists (select 1 from exercicios where nome = 'Press de Ombros com Halteres / Kettlebells');
  select id into ex_id from exercicios where nome = 'Press de Ombros com Halteres / Kettlebells';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Press Arnold' where not exists (select 1 from exercicios where nome = 'Press Arnold');
  select id into ex_id from exercicios where nome = 'Press Arnold';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Elevações Laterais (Halteres / Polia / Elástico)' where not exists (select 1 from exercicios where nome = 'Elevações Laterais (Halteres / Polia / Elástico)');
  select id into ex_id from exercicios where nome = 'Elevações Laterais (Halteres / Polia / Elástico)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Elevações Frontais (Barra / Disco / Polia)' where not exists (select 1 from exercicios where nome = 'Elevações Frontais (Barra / Disco / Polia)');
  select id into ex_id from exercicios where nome = 'Elevações Frontais (Barra / Disco / Polia)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Voos Posteriores / Reverse Flyes (Halteres / Polia)' where not exists (select 1 from exercicios where nome = 'Voos Posteriores / Reverse Flyes (Halteres / Polia)');
  select id into ex_id from exercicios where nome = 'Voos Posteriores / Reverse Flyes (Halteres / Polia)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Face Pull na Polia Alta com Corda' where not exists (select 1 from exercicios where nome = 'Face Pull na Polia Alta com Corda');
  select id into ex_id from exercicios where nome = 'Face Pull na Polia Alta com Corda';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada Alta (Upright Row)' where not exists (select 1 from exercicios where nome = 'Remada Alta (Upright Row)');
  select id into ex_id from exercicios where nome = 'Remada Alta (Upright Row)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Braços — Bíceps e Antebraço', 'Flexores do cotovelo e preensão', 11) returning id into cat_id;
  insert into exercicios (nome) select 'Biceps Curl com Barra / Halteres' where not exists (select 1 from exercicios where nome = 'Biceps Curl com Barra / Halteres');
  select id into ex_id from exercicios where nome = 'Biceps Curl com Barra / Halteres';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Biceps Curl Banco Inclinado' where not exists (select 1 from exercicios where nome = 'Biceps Curl Banco Inclinado');
  select id into ex_id from exercicios where nome = 'Biceps Curl Banco Inclinado';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Hammer Curl / Bíceps Martelo (Halteres / Kettlebells / Corda)' where not exists (select 1 from exercicios where nome = 'Hammer Curl / Bíceps Martelo (Halteres / Kettlebells / Corda)');
  select id into ex_id from exercicios where nome = 'Hammer Curl / Bíceps Martelo (Halteres / Kettlebells / Corda)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Biceps Curl Concentrado' where not exists (select 1 from exercicios where nome = 'Biceps Curl Concentrado');
  select id into ex_id from exercicios where nome = 'Biceps Curl Concentrado';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Zottman Curl' where not exists (select 1 from exercicios where nome = 'Zottman Curl');
  select id into ex_id from exercicios where nome = 'Zottman Curl';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Biceps Curl no TRX / Polia Alta' where not exists (select 1 from exercicios where nome = 'Biceps Curl no TRX / Polia Alta');
  select id into ex_id from exercicios where nome = 'Biceps Curl no TRX / Polia Alta';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Flexão / Extensão de Pulsos com Barra' where not exists (select 1 from exercicios where nome = 'Flexão / Extensão de Pulsos com Barra');
  select id into ex_id from exercicios where nome = 'Flexão / Extensão de Pulsos com Barra';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Plate Pinch Carry (Pega de Dedos)' where not exists (select 1 from exercicios where nome = 'Plate Pinch Carry (Pega de Dedos)');
  select id into ex_id from exercicios where nome = 'Plate Pinch Carry (Pega de Dedos)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Braços — Tríceps', 'Extensores do cotovelo', 12) returning id into cat_id;
  insert into exercicios (nome) select 'Extensão de Tríceps na Polia (Corda / Barra Reta / Barra V)' where not exists (select 1 from exercicios where nome = 'Extensão de Tríceps na Polia (Corda / Barra Reta / Barra V)');
  select id into ex_id from exercicios where nome = 'Extensão de Tríceps na Polia (Corda / Barra Reta / Barra V)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Tríceps Testa / Skullcrusher (Barra / Halteres)' where not exists (select 1 from exercicios where nome = 'Tríceps Testa / Skullcrusher (Barra / Halteres)');
  select id into ex_id from exercicios where nome = 'Tríceps Testa / Skullcrusher (Barra / Halteres)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Press Francês à Cabeça (Halter / Polia)' where not exists (select 1 from exercicios where nome = 'Press Francês à Cabeça (Halter / Polia)');
  select id into ex_id from exercicios where nome = 'Press Francês à Cabeça (Halter / Polia)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Supino com Pegada Fechada' where not exists (select 1 from exercicios where nome = 'Supino com Pegada Fechada');
  select id into ex_id from exercicios where nome = 'Supino com Pegada Fechada';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Fundos em Barras Paralelas' where not exists (select 1 from exercicios where nome = 'Fundos em Barras Paralelas');
  select id into ex_id from exercicios where nome = 'Fundos em Barras Paralelas';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Fundos no Banco (Bench Dips)' where not exists (select 1 from exercicios where nome = 'Fundos no Banco (Bench Dips)');
  select id into ex_id from exercicios where nome = 'Fundos no Banco (Bench Dips)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Extensão de Tríceps no TRX' where not exists (select 1 from exercicios where nome = 'Extensão de Tríceps no TRX');
  select id into ex_id from exercicios where nome = 'Extensão de Tríceps no TRX';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Coice de Tríceps (Kickback) com Halter' where not exists (select 1 from exercicios where nome = 'Coice de Tríceps (Kickback) com Halter');
  select id into ex_id from exercicios where nome = 'Coice de Tríceps (Kickback) com Halter';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Abdominal (Parede Abdominal Direta)', 'Flexão de tronco e de anca, reto abdominal e oblíquos', 13) returning id into cat_id;
  insert into exercicios (nome) select 'Crunch Tradicional na Bola Suíça' where not exists (select 1 from exercicios where nome = 'Crunch Tradicional na Bola Suíça');
  select id into ex_id from exercicios where nome = 'Crunch Tradicional na Bola Suíça';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Crunch Invertido na Bola Suíça / TRX' where not exists (select 1 from exercicios where nome = 'Crunch Invertido na Bola Suíça / TRX');
  select id into ex_id from exercicios where nome = 'Crunch Invertido na Bola Suíça / TRX';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Elevação de Pernas / Joelhos Suspenso na Barra' where not exists (select 1 from exercicios where nome = 'Elevação de Pernas / Joelhos Suspenso na Barra');
  select id into ex_id from exercicios where nome = 'Elevação de Pernas / Joelhos Suspenso na Barra';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Elevação de Pernas em Banco Inclinado' where not exists (select 1 from exercicios where nome = 'Elevação de Pernas em Banco Inclinado');
  select id into ex_id from exercicios where nome = 'Elevação de Pernas em Banco Inclinado';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Abdominal "Canivete"' where not exists (select 1 from exercicios where nome = 'Abdominal "Canivete"');
  select id into ex_id from exercicios where nome = 'Abdominal "Canivete"';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Russian Twist (Disco / Kettlebell / Bola Suíça)' where not exists (select 1 from exercicios where nome = 'Russian Twist (Disco / Kettlebell / Bola Suíça)');
  select id into ex_id from exercicios where nome = 'Russian Twist (Disco / Kettlebell / Bola Suíça)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Mountain Climbers (Chão / Sliders / Bosu)' where not exists (select 1 from exercicios where nome = 'Mountain Climbers (Chão / Sliders / Bosu)');
  select id into ex_id from exercicios where nome = 'Mountain Climbers (Chão / Sliders / Bosu)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('A', 'Core (Estabilização Global)', 'Anti-extensão, anti-rotação e anti-inclinação', 14) returning id into cat_id;
  insert into exercicios (nome) select 'Prancha Frontal (Chão / Bosu / Bola Suíça)' where not exists (select 1 from exercicios where nome = 'Prancha Frontal (Chão / Bosu / Bola Suíça)');
  select id into ex_id from exercicios where nome = 'Prancha Frontal (Chão / Bosu / Bola Suíça)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Prancha Lateral (Chão / Bosu / TRX)' where not exists (select 1 from exercicios where nome = 'Prancha Lateral (Chão / Bosu / TRX)');
  select id into ex_id from exercicios where nome = 'Prancha Lateral (Chão / Bosu / TRX)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Rollout de Abdominais (Bola Suíça / TRX / Sliders)' where not exists (select 1 from exercicios where nome = 'Rollout de Abdominais (Bola Suíça / TRX / Sliders)');
  select id into ex_id from exercicios where nome = 'Rollout de Abdominais (Bola Suíça / TRX / Sliders)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Pallof Press na Polia / Elástico (Ajoelhado / Em pé)' where not exists (select 1 from exercicios where nome = 'Pallof Press na Polia / Elástico (Ajoelhado / Em pé)');
  select id into ex_id from exercicios where nome = 'Pallof Press na Polia / Elástico (Ajoelhado / Em pé)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Farmer''s Carry / Suitcase Carry / Overhead Carry' where not exists (select 1 from exercicios where nome = 'Farmer''s Carry / Suitcase Carry / Overhead Carry');
  select id into ex_id from exercicios where nome = 'Farmer''s Carry / Suitcase Carry / Overhead Carry';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Woodchopper na Polia (Alta-Baixa / Baixa-Alta)' where not exists (select 1 from exercicios where nome = 'Woodchopper na Polia (Alta-Baixa / Baixa-Alta)');
  select id into ex_id from exercicios where nome = 'Woodchopper na Polia (Alta-Baixa / Baixa-Alta)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Dead Bug / Bird-Dog (Chão / Bosu / Bola Suíça)' where not exists (select 1 from exercicios where nome = 'Dead Bug / Bird-Dog (Chão / Bosu / Bola Suíça)');
  select id into ex_id from exercicios where nome = 'Dead Bug / Bird-Dog (Chão / Bosu / Bola Suíça)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Extensão Lombar / Hiperextensão na Bola Suíça' where not exists (select 1 from exercicios where nome = 'Extensão Lombar / Hiperextensão na Bola Suíça');
  select id into ex_id from exercicios where nome = 'Extensão Lombar / Hiperextensão na Bola Suíça';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Força Máxima / Carga Elevada', 'Multiarticulares estruturais', 15) returning id into cat_id;
  insert into exercicios (nome) select 'Agachamento Back Squat com Barra' where not exists (select 1 from exercicios where nome = 'Agachamento Back Squat com Barra');
  select id into ex_id from exercicios where nome = 'Agachamento Back Squat com Barra';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Supino Plano com Barra' where not exists (select 1 from exercicios where nome = 'Supino Plano com Barra');
  select id into ex_id from exercicios where nome = 'Supino Plano com Barra';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Peso Morto Convencional / Sumô' where not exists (select 1 from exercicios where nome = 'Peso Morto Convencional / Sumô');
  select id into ex_id from exercicios where nome = 'Peso Morto Convencional / Sumô';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Press Militar em pé com Barra' where not exists (select 1 from exercicios where nome = 'Press Militar em pé com Barra');
  select id into ex_id from exercicios where nome = 'Press Militar em pé com Barra';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Leg Press 45º com Carga' where not exists (select 1 from exercicios where nome = 'Leg Press 45º com Carga');
  select id into ex_id from exercicios where nome = 'Leg Press 45º com Carga';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Hip Thrust com Barra Olímpica' where not exists (select 1 from exercicios where nome = 'Hip Thrust com Barra Olímpica');
  select id into ex_id from exercicios where nome = 'Hip Thrust com Barra Olímpica';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Força Explosiva e Potência', 'Taxa de produção de força (RFD)', 16) returning id into cat_id;
  insert into exercicios (nome) select 'Wallball Shots' where not exists (select 1 from exercicios where nome = 'Wallball Shots');
  select id into ex_id from exercicios where nome = 'Wallball Shots';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Slam Ball Overhead / Rotational Slams' where not exists (select 1 from exercicios where nome = 'Slam Ball Overhead / Rotational Slams');
  select id into ex_id from exercicios where nome = 'Slam Ball Overhead / Rotational Slams';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Kettlebell Snatch / Clean & Press' where not exists (select 1 from exercicios where nome = 'Kettlebell Snatch / Clean & Press');
  select id into ex_id from exercicios where nome = 'Kettlebell Snatch / Clean & Press';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Push Press com Barra / Kettlebells' where not exists (select 1 from exercicios where nome = 'Push Press com Barra / Kettlebells');
  select id into ex_id from exercicios where nome = 'Push Press com Barra / Kettlebells';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Lançamento de Peito com Bola Medicinal (Chest Pass)' where not exists (select 1 from exercicios where nome = 'Lançamento de Peito com Bola Medicinal (Chest Pass)');
  select id into ex_id from exercicios where nome = 'Lançamento de Peito com Bola Medicinal (Chest Pass)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Flexões Pliométricas / com Palma' where not exists (select 1 from exercicios where nome = 'Flexões Pliométricas / com Palma');
  select id into ex_id from exercicios where nome = 'Flexões Pliométricas / com Palma';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Pliométricos e Agilidade', 'Saltos, reatividade e desaceleração', 17) returning id into cat_id;
  insert into exercicios (nome) select 'Box Jumps (Salto para Box)' where not exists (select 1 from exercicios where nome = 'Box Jumps (Salto para Box)');
  select id into ex_id from exercicios where nome = 'Box Jumps (Salto para Box)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento com Salto (Jump Squat) no Trampolim / Chão' where not exists (select 1 from exercicios where nome = 'Agachamento com Salto (Jump Squat) no Trampolim / Chão');
  select id into ex_id from exercicios where nome = 'Agachamento com Salto (Jump Squat) no Trampolim / Chão';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Step-Downs com Salto Controlado' where not exists (select 1 from exercicios where nome = 'Step-Downs com Salto Controlado');
  select id into ex_id from exercicios where nome = 'Step-Downs com Salto Controlado';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Saltos Laterais no Step / Bosu' where not exists (select 1 from exercicios where nome = 'Saltos Laterais no Step / Bosu');
  select id into ex_id from exercicios where nome = 'Saltos Laterais no Step / Bosu';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Saltos Contínuos no Trampolim' where not exists (select 1 from exercicios where nome = 'Saltos Contínuos no Trampolim');
  select id into ex_id from exercicios where nome = 'Saltos Contínuos no Trampolim';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Burpees com Salto para Box' where not exists (select 1 from exercicios where nome = 'Burpees com Salto para Box');
  select id into ex_id from exercicios where nome = 'Burpees com Salto para Box';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Unilaterais / Correção de Assimetrias', 'Equilíbrio de força e estabilidade articular', 18) returning id into cat_id;
  insert into exercicios (nome) select 'Agachamento Búlgaro' where not exists (select 1 from exercicios where nome = 'Agachamento Búlgaro');
  select id into ex_id from exercicios where nome = 'Agachamento Búlgaro';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Step-Up no Banco / Box' where not exists (select 1 from exercicios where nome = 'Step-Up no Banco / Box');
  select id into ex_id from exercicios where nome = 'Step-Up no Banco / Box';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'RDL Unilateral (Single-Leg RDL)' where not exists (select 1 from exercicios where nome = 'RDL Unilateral (Single-Leg RDL)');
  select id into ex_id from exercicios where nome = 'RDL Unilateral (Single-Leg RDL)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada Unilateral ("Serrote")' where not exists (select 1 from exercicios where nome = 'Remada Unilateral ("Serrote")');
  select id into ex_id from exercicios where nome = 'Remada Unilateral ("Serrote")';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Press de Ombros Unilateral com Halter' where not exists (select 1 from exercicios where nome = 'Press de Ombros Unilateral com Halter');
  select id into ex_id from exercicios where nome = 'Press de Ombros Unilateral com Halter';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Hip Thrust Unilateral' where not exists (select 1 from exercicios where nome = 'Hip Thrust Unilateral');
  select id into ex_id from exercicios where nome = 'Hip Thrust Unilateral';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Leg Press Unilateral' where not exists (select 1 from exercicios where nome = 'Leg Press Unilateral');
  select id into ex_id from exercicios where nome = 'Leg Press Unilateral';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Extensão / Flexão Unilateral na Polia' where not exists (select 1 from exercicios where nome = 'Extensão / Flexão Unilateral na Polia');
  select id into ex_id from exercicios where nome = 'Extensão / Flexão Unilateral na Polia';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Condicionamento Cardiorrespiratório e HIIT', 'Estímulos metabólicos de alta densidade', 19) returning id into cat_id;
  insert into exercicios (nome) select 'Sprints na Air Bike' where not exists (select 1 from exercicios where nome = 'Sprints na Air Bike');
  select id into ex_id from exercicios where nome = 'Sprints na Air Bike';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Séries de Tiro no Remo Ergométrico' where not exists (select 1 from exercicios where nome = 'Séries de Tiro no Remo Ergométrico');
  select id into ex_id from exercicios where nome = 'Séries de Tiro no Remo Ergométrico';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Passadeira Inclinada / Sprints' where not exists (select 1 from exercicios where nome = 'Passadeira Inclinada / Sprints');
  select id into ex_id from exercicios where nome = 'Passadeira Inclinada / Sprints';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Saco de Boxe (Combinações Jab-Directo-Cruzado)' where not exists (select 1 from exercicios where nome = 'Saco de Boxe (Combinações Jab-Directo-Cruzado)');
  select id into ex_id from exercicios where nome = 'Saco de Boxe (Combinações Jab-Directo-Cruzado)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Sprints e Cadência Elevada na Bicicleta de Cycling' where not exists (select 1 from exercicios where nome = 'Sprints e Cadência Elevada na Bicicleta de Cycling');
  select id into ex_id from exercicios where nome = 'Sprints e Cadência Elevada na Bicicleta de Cycling';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Circuito Contínuo na Elíptica' where not exists (select 1 from exercicios where nome = 'Circuito Contínuo na Elíptica');
  select id into ex_id from exercicios where nome = 'Circuito Contínuo na Elíptica';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Estabilidade e Equilíbrio (Aparelhos Instáveis)', 'Proprioceção e estabilizadores profundos', 20) returning id into cat_id;
  insert into exercicios (nome) select 'Agachamento no Bosu (Lado bolha ou plano)' where not exists (select 1 from exercicios where nome = 'Agachamento no Bosu (Lado bolha ou plano)');
  select id into ex_id from exercicios where nome = 'Agachamento no Bosu (Lado bolha ou plano)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento com Bola Suíça na Parede' where not exists (select 1 from exercicios where nome = 'Agachamento com Bola Suíça na Parede');
  select id into ex_id from exercicios where nome = 'Agachamento com Bola Suíça na Parede';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Flexões sobre o Bosu / Bola Medicinal' where not exists (select 1 from exercicios where nome = 'Flexões sobre o Bosu / Bola Medicinal');
  select id into ex_id from exercicios where nome = 'Flexões sobre o Bosu / Bola Medicinal';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Prancha na Bola Suíça / Bosu' where not exists (select 1 from exercicios where nome = 'Prancha na Bola Suíça / Bosu');
  select id into ex_id from exercicios where nome = 'Prancha na Bola Suíça / Bosu';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Bird-Dog no Bosu' where not exists (select 1 from exercicios where nome = 'Bird-Dog no Bosu');
  select id into ex_id from exercicios where nome = 'Bird-Dog no Bosu';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Agachamento Búlgaro no TRX' where not exists (select 1 from exercicios where nome = 'Agachamento Búlgaro no TRX');
  select id into ex_id from exercicios where nome = 'Agachamento Búlgaro no TRX';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Calistenia / Peso Corporal', 'O próprio corpo como resistência', 21) returning id into cat_id;
  insert into exercicios (nome) select 'Elevações na Barra Fixa (Pull-ups / Chin-ups)' where not exists (select 1 from exercicios where nome = 'Elevações na Barra Fixa (Pull-ups / Chin-ups)');
  select id into ex_id from exercicios where nome = 'Elevações na Barra Fixa (Pull-ups / Chin-ups)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Flexões de Braços (Push-ups)' where not exists (select 1 from exercicios where nome = 'Flexões de Braços (Push-ups)');
  select id into ex_id from exercicios where nome = 'Flexões de Braços (Push-ups)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Fundos em Barras Paralelas / Banco' where not exists (select 1 from exercicios where nome = 'Fundos em Barras Paralelas / Banco');
  select id into ex_id from exercicios where nome = 'Fundos em Barras Paralelas / Banco';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Pistol Squats / Step-Downs' where not exists (select 1 from exercicios where nome = 'Pistol Squats / Step-Downs');
  select id into ex_id from exercicios where nome = 'Pistol Squats / Step-Downs';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Pranchas e Variações de Core' where not exists (select 1 from exercicios where nome = 'Pranchas e Variações de Core');
  select id into ex_id from exercicios where nome = 'Pranchas e Variações de Core';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Inverted Rows no TRX' where not exists (select 1 from exercicios where nome = 'Inverted Rows no TRX');
  select id into ex_id from exercicios where nome = 'Inverted Rows no TRX';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Tração Metabólica / Grip Strength', 'Resistência da pega e antebraços', 22) returning id into cat_id;
  insert into exercicios (nome) select 'Farmer''s Carry com Halter / Kettlebell Pesado' where not exists (select 1 from exercicios where nome = 'Farmer''s Carry com Halter / Kettlebell Pesado');
  select id into ex_id from exercicios where nome = 'Farmer''s Carry com Halter / Kettlebell Pesado';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Plate Pinch Carry (segurar discos com os dedos)' where not exists (select 1 from exercicios where nome = 'Plate Pinch Carry (segurar discos com os dedos)');
  select id into ex_id from exercicios where nome = 'Plate Pinch Carry (segurar discos com os dedos)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Suitcase Carry' where not exists (select 1 from exercicios where nome = 'Suitcase Carry');
  select id into ex_id from exercicios where nome = 'Suitcase Carry';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Dead Hang na Barra de Elevações (Suspensão Isométrica)' where not exists (select 1 from exercicios where nome = 'Dead Hang na Barra de Elevações (Suspensão Isométrica)');
  select id into ex_id from exercicios where nome = 'Dead Hang na Barra de Elevações (Suspensão Isométrica)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Kettlebell Swings' where not exists (select 1 from exercicios where nome = 'Kettlebell Swings');
  select id into ex_id from exercicios where nome = 'Kettlebell Swings';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Reabilitação / Pré-Habilitação / Mobilidade', 'Baixo impacto, saúde articular e aquecimento', 23) returning id into cat_id;
  insert into exercicios (nome) select 'Clamshell com Elástico' where not exists (select 1 from exercicios where nome = 'Clamshell com Elástico');
  select id into ex_id from exercicios where nome = 'Clamshell com Elástico';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Bird-Dog no Chão' where not exists (select 1 from exercicios where nome = 'Bird-Dog no Chão');
  select id into ex_id from exercicios where nome = 'Bird-Dog no Chão';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Extensão Torácica na Bola Suíça' where not exists (select 1 from exercicios where nome = 'Extensão Torácica na Bola Suíça');
  select id into ex_id from exercicios where nome = 'Extensão Torácica na Bola Suíça';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Adutor Copenhaga (versão modificada)' where not exists (select 1 from exercicios where nome = 'Adutor Copenhaga (versão modificada)');
  select id into ex_id from exercicios where nome = 'Adutor Copenhaga (versão modificada)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Pallof Press leve com Elástico' where not exists (select 1 from exercicios where nome = 'Pallof Press leve com Elástico');
  select id into ex_id from exercicios where nome = 'Pallof Press leve com Elástico';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Caminhada no Trampolim (Baixo Impacto)' where not exists (select 1 from exercicios where nome = 'Caminhada no Trampolim (Baixo Impacto)');
  select id into ex_id from exercicios where nome = 'Caminhada no Trampolim (Baixo Impacto)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Grupo / Circuito / Pump', 'Treino em dupla ou pequenos grupos', 24) returning id into cat_id;
  insert into exercicios (nome) select 'Agachamento Pump com Barra Pequena' where not exists (select 1 from exercicios where nome = 'Agachamento Pump com Barra Pequena');
  select id into ex_id from exercicios where nome = 'Agachamento Pump com Barra Pequena';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Remada Curvada Pump' where not exists (select 1 from exercicios where nome = 'Remada Curvada Pump');
  select id into ex_id from exercicios where nome = 'Remada Curvada Pump';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Clean & Press com Barra de Pump' where not exists (select 1 from exercicios where nome = 'Clean & Press com Barra de Pump');
  select id into ex_id from exercicios where nome = 'Clean & Press com Barra de Pump';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Lunge Estático com Barra de Pump' where not exists (select 1 from exercicios where nome = 'Lunge Estático com Barra de Pump');
  select id into ex_id from exercicios where nome = 'Lunge Estático com Barra de Pump';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Biceps & Tríceps Pump com Barra / Discos Pequenos' where not exists (select 1 from exercicios where nome = 'Biceps & Tríceps Pump com Barra / Discos Pequenos');
  select id into ex_id from exercicios where nome = 'Biceps & Tríceps Pump com Barra / Discos Pequenos';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

  insert into categorias (parte, nome, nota, ordem) values ('B', 'Discos Deslizantes (Sliders)', 'Fricção e controlo excêntrico exigente', 25) returning id into cat_id;
  insert into exercicios (nome) select 'Flexão de Joelhos com Discos Deslizantes' where not exists (select 1 from exercicios where nome = 'Flexão de Joelhos com Discos Deslizantes');
  select id into ex_id from exercicios where nome = 'Flexão de Joelhos com Discos Deslizantes';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Lunge com Discos Deslizantes (Slide Lunge)' where not exists (select 1 from exercicios where nome = 'Lunge com Discos Deslizantes (Slide Lunge)');
  select id into ex_id from exercicios where nome = 'Lunge com Discos Deslizantes (Slide Lunge)';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Flexões com Abertura Lateral em Disco' where not exists (select 1 from exercicios where nome = 'Flexões com Abertura Lateral em Disco');
  select id into ex_id from exercicios where nome = 'Flexões com Abertura Lateral em Disco';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Mountain Climbers com Sliders' where not exists (select 1 from exercicios where nome = 'Mountain Climbers com Sliders');
  select id into ex_id from exercicios where nome = 'Mountain Climbers com Sliders';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);
  insert into exercicios (nome) select 'Rollout de Abdominais com Sliders' where not exists (select 1 from exercicios where nome = 'Rollout de Abdominais com Sliders');
  select id into ex_id from exercicios where nome = 'Rollout de Abdominais com Sliders';
  insert into exercicios_categorias (exercicio_id, categoria_id) values (ex_id, cat_id);

end $$;
